name: audit

on:
- workflow_dispatch

jobs:
  test:
    runs-on: macos-14
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Tap Formula
      run: brew tap tuist/tuist

    - name: Audit Formula
      run: brew audit --strict --online tuist

    - name: Install Formula
      run: brew install tuist

    - name: Create Brewage
      run: |
        sudo sysadminctl -addUser brewage -password brewage -admin
        sudo chown -R brewage "$(brew --prefix)/Homebrew"

    - name: Test Formula
      run: echo brewage | sudo -S -u brewage brew test tuist
