name: Release Cask

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version for which the cask will be generated
        required: true
      sha256:
        description: The sha256 of the Tuist.app file associated to the version
        required: true

permissions:
  contents: write

env:
  MISE_EXPERIMENTAL: 1

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        run: |
          bundle install
      - name: Generate formula
        run: |
          mise run release-cask -- -v ${{ github.event.inputs.version }} -s ${{ github.event.inputs.sha256 }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Release ${{ github.event.inputs.version }}"
